site_name: NaDGenLib Docs
site_url: https://larry0716.github.io
site_author: Larry Green
strict: false

theme: 
  name: null
  custom_dir: 'mkdocs-material/material'
  palette:
    - scheme: default
      primary: white
      accent: red
      toggle:
        icon: material/brightness-7
        name: 切换至夜间模式
    - scheme: slate
      primary: black
      accent: white
      toggle: 
        icon: material/brightness-4
        name: 切换至白天模式
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.top
    - search.suggest
    - search.highlight
    - navigation.expand
    - search.share
  language: zh
  icon:
    repo: fontawesome/brands/github
  font:
    text: 'Fira Sans'
    code: 'Fira Mono'

edit_uri: edit/main/docs
repo_url: https://github.com/larry0716/NaDGenLib
repo_name: NaDGenLib

copyright: Copyright &copy; 2023 Larry Green

hooks:
  - hooks/on_env.py

extra:
  generator: true
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/larry0716
    - icon: fontawesome/brands/bilibili
      link: https://space.bilibili.com/408496889
    - icon: fontawesome/solid/paper-plane
      link: mailto:<larry0716@163.com>

nav: 
  - Home: 
    - 开始: index.md
  - 文档:
    - 0. 简介: NaDGenLib-docs/README.md
    - 1. 开始: NaDGenLib-docs/startup.md

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
      # slugify: !!python/name:pymdownx.slugs.uslugify
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.highlight:
      linenums: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.snippets
  - pymdownx.progressbar
  - pymdownx.smartsymbols
  - pymdownx.superfences:
      custom_fences:
        - name: math
          class: arithmatex
          format: !!python/name:pymdownx.arithmatex.fence_mathjax_format
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true

extra_javascript:
  - '_static/js/math-csr.js?math-csr'
  - 'assets/vendor/mathjax/es5/tex-mml-chtml.js?math-csr'

extra_css:
  - '_static/css/extra.css?v=14'
